## Basic Configuration

baseurl = "https://shenoybr.github.io/hugo-goa-demo/" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Alessandra Valcarcel"
title = "Alessandra Valcarcel"

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Alessandra Valcarcel"
intro = "PhD Candidate"
description = "Studying biostatistics at the University of Pennsylvania under Dr. Russell [Taki] Shinohara"
authorimage = "me.png"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "avalcarcel9"
linkedin = "<username>"
google = "<username>"
email = "you@example.com"

## Extras
[params.extra]
copyright = "Â© 2018. Alessandra Valcarcel. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = true
highlightjs = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "coderag"
    identifier = "coderag"
    weight = 300
    url = "/coderag/"
